server:
  port: ${SERVER_PORT:9543}

postgres:
  enabled: ${ENABLE_POSTGRES:false}
  host: ${POSTGRES_HOST:localhost}
  port: ${POSTGRES_PORT:5432}
  db: ${POSTGRES_DB:postgres_demo}
  user: ${POSTGRES_USER:postgres}
  password: ${POSTGRES_PASSWORD:pass}

