apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: demo
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "frontend-ui:kube"
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 8888
      targetPort: 80
  selector:
    app: demo
    tier: frontend
  type: NodePort
