apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: demo
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: "contract-service:kube"
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: demo
    tier: backend
