apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: demo
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: "contract-service:kube"
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/readiness
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 300
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 60
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: demo
    tier: backend
