apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-service
spec:
  selector:
    matchLabels:
      app: contract
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: contract
        tier: backend
        track: stable
    spec:
      containers:
        - name: contract-service
          image: "contract-service:kube"
          ports:
            - name: http
              containerPort: 6000
