apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
spec:
  selector:
    app: contract
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
spec:
  selector:
    matchLabels:
      app: contract
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: contract
        tier: frontend
        track: stable
    spec:
      containers:
      - name: frontend-ui
        image: "frontend-ui:kube"
